## 389. Find the Difference

## String t is generated by random shuffling string s and then add one more letter at a random position.

from functools import reduce
def findTheDifference(s, t):
    s_dict={}
    t_dict={}
    for char in s:
        s_dict[char]=s_dict.get(char,0)+1
    for char in t:
        t_dict[char]=t_dict.get(char,0)+1
    for key in t:
        if key not in s or t_dict[key]!=s_dict[key]:
            return key
        
def findTheDifference2(s, t):
    temp=map(ord,s+t)
    result=chr(reduce(lambda x,y:x^y, temp))
    return result

        
if __name__=='__main__':
    s, t = "abcd", "abcde"
    print(findTheDifference2(s,t))